// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initialupdate17102024 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialupdate17102024));
        
        string IMigrationMetadata.Id
        {
            get { return "202410170639340_initialupdate17102024"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
